web/config/routes.rb
Blabla::Application.routes.draw do

  resources :stocks

  resources :quantites

  resources :productions

  resources :commandes

  resources :patrons

  resources :infos

  resources :versions

  resources :modeles

  resources :couleurs

  resources :agents
  resources :clients
  resources :retours

  root 'commandes#index'

end

web/app/models/agent.rb
# == Schema Information
#
# Table name: agents
#
#  id         :integer          not null, primary key
#  nom        :string(255)
#  email      :text
#  telephone  :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Agent < ApplicationRecord

  # relations
  has_many :clients
  has_one :patron

  # validations
  validates_presence_of :nom, :email, :telephone
  validates_uniqueness_of :nom
  validates :email, email: true
  validates_format_of :telephone, :with => /[0-9]{10}/
  before_validation :format_phone
  def format_phone
    self.telephone = (self.telephone || "").gsub(/[^\d]/,'')
  end

  def portefeuille
    self.clients.collect { |client|
      commandes = client.commandes.where(status: 3)
      {
        societe: client.societe,
        nbCommandes: commandes.count,
        total_net_ht: commandes.inject(0){|s,commande| s+commande.montant_net_ht},
        total_tva: commandes.inject(0){|s,commande| s+commande.tva},
        total_ttc: commandes.inject(0){|s,commande| s+commande.montant_ttc}
      }
    }
  end

  def performance_net_ht
    self.portefeuille.inject(0){|s,c| s+c[:total_net_ht]}
  end

  def performance_tva
    self.portefeuille.inject(0){|s,c| s+c[:total_tva]}
  end

  def performance_ttc
    self.portefeuille.inject(0){|s,c| s+c[:total_ttc]}
  end

end

web/app/controllers/agents_controller.rb
class AgentsController < ApplicationController
  before_action :set_agent, only: [:show, :edit, :update, :destroy]

  # GET /agents
  def index
    @agents = Agent.all().order(:nom)
  end

  # GET /agents/new
  def new
    @agent = Agent.new
  end

  def show
    if @agent.patron
      redirect_to patrons_path
    end
  end

  # GET /agents/1/edit
  def edit
  end

  # POST /agents
  def create
    @agent = Agent.new(agent_params)
    if @agent.valid? && @agent.save
      redirect_to agent_path(@agent)
    else
      render action: 'new'
    end
  end

  # PUT /agents/1
  def update
      if @agent.update(agent_params)
        redirect_to agent_path(@agent)
      else
        render action: 'edit'
      end
  end

  # DELETE /agents/1
  def destroy
    @agent.destroy
    redirect_to agents_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_agent
      @agent = Agent.includes(:clients, :clients => :commandes).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def agent_params
      params.require(:agent).permit!
    end
end

web/app/helpers/agents_helper.rb
module AgentsHelper
end

web/app/views/agents/_form.html.haml
= render "/application/errors", :record => @agent

%h2 Coordonnées

= form_for @agent, :method=>(@agent.id ? :put : :post) do |f|
  = f.hidden_field :id

  = f.label :nom, 'Nom'
  = f.text_field :nom
  %br
  = f.label :email, 'E-mail'
  = f.email_field :email
  %br
  = f.label :telephone, 'Telephone'
  = f.phone_field :telephone

web/app/views/agents/edit.html.haml
%h1 Agents :: modifier
.actions2
  = link_to 'Retour', agent_path(@agent)
  \/
  %a{href: "/", onclick: "document.forms[0].submit(); return false;"} Enregistrer


= render 'form'

web/app/views/agents/index.html.haml
%h1 Agents
.actions2
  = link_to ' + Ajouter un agent', new_agent_path()

%table.listing
  %tr
    %th{width: "150px;"} Nom
    %th E-mail

  - @agents.each do |agent|
    %tr{onclick: "window.location = $(this).attr('url')", url: agent_path(agent)}
      %td= agent.nom
      %td= agent.email

web/app/views/agents/new.html.haml
%h1 Agent :: créer
.actions2
  = link_to 'Retour', agents_path
  \/
  %a{href: "/", onclick: "document.forms[0].submit(); return false;"} Enregistrer

= render 'form'

web/app/views/agents/show.html.haml
%h1 Agent
.actions2
  = link_to 'Retour', agents_path
  \/
  = link_to "Modifier", edit_agent_path(@agent)
  \/
  = link_to 'Supprimer', @agent, :method => :delete, :data => { :confirm => 'Etes-vous sur de vouloir supprimer cet agent ?' }

%h2 Coordonnées

%dl
  %dt= "Nom"
  %dd= @agent.nom

  %dt= "E-mail"
  %dd= @agent.email

  %dt= "Téléphone"
  %dd= @agent.telephone

  %h2 Portefeuille

  %dl
    %dt= "Nb. de clients suivis"
    %dd= @agent.clients.count
    %dt= "Performance HT"
    %dd
      != prix(@agent.performance_net_ht)
    %dt= "Performance TVA"
    %dd
      != prix(@agent.performance_tva)
    %dt= "Performance TTC"
    %dd
      != prix(@agent.performance_ttc)
    %table.listing
      %tr
        %th Client
        %th{width: "50px;"} # commandes
        %th{width: "100px;"} Total HT
        %th{width: "100px;"} Total TVA
        %th{width: "100px;"} Total à payer
      - @agent.portefeuille.each do |client|
        %tr{style: client[:nbCommandes] == 0 ? 'color:#AAA;' : nil}
          %td= client[:societe]
          %td{class: "center"}= client[:nbCommandes]
          %td{class: "right"}!= client[:nbCommandes] > 0 ? prix(client[:total_net_ht]) : '-'
          %td{class: "right"}!= client[:nbCommandes] > 0 ? prix(client[:total_tva]) : '-'
          %td{class: "right"}!= client[:nbCommandes] > 0 ? prix(client[:total_ttc]) : '-'