web/config/routes.rb
Blabla::Application.routes.draw do

  resources :stocks

  resources :quantites

  resources :productions

  resources :commandes

  resources :patrons

  resources :infos

  resources :versions

  resources :modeles

  resources :couleurs

  resources :agents
  resources :clients
  resources :retours

  root 'commandes#index'

end

web/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate


  protected
      def authenticate
        authenticate_or_request_with_http_basic do |username, password|
          username == USER_ID && password == PASSWORD
        end
      end
end

web/app/helpers/application_helper.rb
module ApplicationHelper
  
  def logged_in?
     not request.authorization.nil?
   end
   
end

web/app/views/application/_errors.haml
- if record.errors.any?
  #error_explanation
    .erreurs
      %ul
        - record.errors.messages.each do |msg|
          %li= msg[1][0]

web/app/views/application/_menu.haml
#navigation
 = link_to_unless(params[:controller] == 'couleurs',"couleurs",couleurs_path)
 = link_to_unless(params[:controller] == 'modeles',"modeles",modeles_path)
 = link_to_unless(params[:controller] == 'commandes',"commandes",commandes_path)
 = link_to_unless(params[:controller] == 'retours',"retours",retours_path)
 = link_to_unless(params[:controller] == 'productions',"productions",productions_path)
 = link_to_unless(params[:controller] == 'clients',"clients",clients_path)
 = link_to_unless(params[:controller] == 'agents',"agents",agents_path)
 = link_to_unless(params[:controller] == 'patrons',"infos",patrons_path)