web/config/routes.rb
Blabla::Application.routes.draw do

  resources :stocks

  resources :quantites

  resources :productions

  resources :commandes

  resources :patrons

  resources :infos

  resources :versions

  resources :modeles

  resources :couleurs

  resources :agents
  resources :clients
  resources :retours

  root 'commandes#index'

end

web/app/models/version.rb
# == Schema Information
#
# Table name: versions
#
#  id            :integer          not null, primary key
#  modele_id     :integer
#  couleurs_1_id :integer
#  couleurs_2_id :integer
#  created_at    :datetime
#  updated_at    :datetime
#

class Version < ApplicationRecord

    # RELATIONS
    belongs_to :modele

    # VALIDATIONS
    validates_presence_of :modele_id, :couleurs_1_id

    # destruction
    before_destroy :ensure_is_in_no_order

    def ensure_is_in_no_order
       if Commande.includes(:quantite).all.to_a.select {|c| c.quantite.de(self) > 0}.present?
         self.errors.add(:couleurs,"Impossible de suppirmer. Cette version de modele est en commande.")
         throw :abort
       end
    end

    # METHODS
    def couleur_1
        Couleur.find(self.couleurs_1_id).nom if self.couleurs_1_id
    end

    def couleur_2
        Couleur.find(self.couleurs_2_id).nom if self.couleurs_2_id
    end

    def couleurs
        [couleur_1, couleur_2].compact.join('/')
    end
end

web/app/controllers/versions_controller.rb
class VersionsController < ApplicationController
  before_action :set_version, only: [:show, :edit, :update, :destroy]

  # GET /versions
  # GET /versions.json
  def index
    @versions = Version.all
  end

  # GET /versions/1
  # GET /versions/1.json
  def show
  end

  # GET /versions/new
  def new
    @version = Version.new
    @modele = Modele.find(params[:modele_id])
  end

  # GET /versions/1/edit
  def edit
  end

  # POST /versions
  # POST /versions.json
  def create
    @version = Version.new(version_params)
      if @version.valid? && @version.save
        redirect_to modele_path(@version.modele)
      else
        render 'new'
      end
  end

  # PATCH/PUT /versions/1
  # PATCH/PUT /versions/1.json
  def update
      if @version.update(version_params)
        redirect_to modele_path(@version.modele)
      else
        render 'edit'
      end
  end

  # DELETE /versions/1
  # DELETE /versions/1.json
  def destroy
    if @version.destroy
      redirect_to modele_path(@version.modele)
    else
      render 'edit'
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_version
      @version = Version.find(params[:id])
      @modele = @version.modele
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def version_params
      params.require(:version).permit!
    end
end

web/app/helpers/versions_helper.rb
module VersionsHelper
end

web/app/views/versions/_form.html.haml
= form_for @version, :method=>(@version.id ? :put : :post) do |f|
  = f.hidden_field :modele_id, value: @modele.id

  %h2 Modèle
  %p= "#{@modele.numero} :: #{@modele.nom}"

  %h2 Couleurs

  = f.label :couleurs_1_id, 'Couleur principale'
  = f.collection_select :couleurs_1_id, Couleur.all, :id, :nom
  %br
  = f.label :couleurs_2_id, 'Couleur secondaire'
  = f.collection_select :couleurs_2_id, Couleur.all, :id, :nom, :include_blank=>true

web/app/views/versions/edit.html.haml
%h1 Catalogue :: modèle :: version :: modifier
.actions2
  = link_to 'Annuler', modele_path(@version.modele)
  \/
  %a{href: "/", onclick: "document.forms[0].submit(); return false;"} Enregistrer
  \/
  = link_to 'Supprimer', @version, :method => :delete, :data => { :confirm => 'Etes-vous sur de vouloir supprimer cette version ?' }

= render "/application/errors", :record => @version

= render 'form'

web/app/views/versions/index.html.haml
%h1 Listing versions

%table
  %tr
    %th
    %th
    %th

  - @versions.each do |version|
    %tr
      %td= link_to 'Show', version
      %td= link_to 'Edit', edit_version_path(version)
      %td= link_to 'Destroy', version, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Version', new_version_path

web/app/views/versions/new.html.haml
%h1 Catalogue :: modèle :: version :: nouvelle
.actions2
  = link_to 'Annuler', modeles_path
  \/
  %a{href: "/", onclick: "document.forms[0].submit(); return false;"} Enregistrer

= render 'form'

web/app/views/versions/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_version_path(@version)
\|
= link_to 'Back', versions_path