web/config/routes.rb
Blabla::Application.routes.draw do

  resources :stocks

  resources :quantites

  resources :productions

  resources :commandes

  resources :patrons

  resources :infos

  resources :versions

  resources :modeles

  resources :couleurs

  resources :agents
  resources :clients
  resources :retours

  root 'commandes#index'

end

web/app/models/commande.rb
# == Schema Information
#
# Table name: commandes
#
#  id               :integer          not null, primary key
#  client_id        :integer
#  livraison        :date
#  commentaire      :text
#  status           :integer          default(0), not null
#  production_id    :integer
#  created_at       :datetime
#  updated_at       :datetime
#  frais_de_port    :float
#  nombre_paiments  :integer
#  numero_facture   :integer
#  date_facturation :date
#

class Commande < ApplicationRecord

  # relations
  belongs_to :client
  belongs_to :production
  has_one :quantite, as: :quantifiable, dependent: :destroy
  accepts_nested_attributes_for :quantite, allow_destroy: true
  has_many :retours

  # validation
  validates_presence_of :client_id
  validates_inclusion_of :status, :in => 0..4
  validate :validations, :on => :create
  validates_uniqueness_of :numero_facture, allow_blank: true
  validates_numericality_of :frais_de_port, :greater_than_than_or_equal_to => 0
  validates_numericality_of :avoir, :greater_than_than_or_equal_to => 0

  def validations
    self.errors.add(:livraison) if self.livraison < Time.now-1.day
    self.errors.add(:quantite) unless self.quantite.de > 0
  end
  before_validation :remove_comma

  def remove_comma
    self[:frais_de_port] = self.read_attribute_before_type_cast('frais_de_port').to_s.gsub(',', '.').to_f
    self[:avoir] = self.read_attribute_before_type_cast('avoir').to_s.gsub(',', '.').to_f
  end

  # SCOPES
  scope :en_avance, -> {where(status: 0)}
  scope :en_production, -> {where(status: 1)}
  scope :en_preparation, -> {where(status: 2)}
  scope :envoyees, -> {where(status: 3)}
  scope :payees, -> {where(status: 4)}


  # initialization

  after_initialize :init
  def init
    self.status ||= 0
    self.frais_de_port ||= 0
    self.avoir ||= 0
  end

  before_save :update_montant
  def update_montant
    modeles_list = Modele.where(id: modeles).to_a
    self[:montant] = modeles_list.collect { |m| montant(m) }.sum
  end

 #delegation
 delegate :modeles, :versions, :de, to: :quantite
 delegate :societe, to: :client

 STATUS_LIST = {0=>"en pré-commande", 1=>"en production", 2=>"en préparation", 3=>"envoyée", 4=>"payée"}

 def prepare
   self.quantite = Quantite.new
      Modele.catalogue.each do |modele|
        modele.versions.each do |version|
          modele.liste_taille.compact.each do |taille|
            self.quantite.set(modele.id,version.id,taille,0)
          end
        end
     end
     self
 end

  # methods
  def date
    livraison.strftime('%d/%m/%y')
  end

  def pasee_le
    created_at.strftime('%d/%m/%y')
  end

  def reference
    status < 3 ? numero_commande : numero_facture
  end

  def numero_commande
    'C' + created_at.strftime('%y') + '-' + ("%03d" % client.id) + '-' + ("%03d" % id)
  end

  def numero_facture
    ('F' + date_facturation.strftime('%y')+'-'+ ("%03d" % client.id) + '-' + ("%03d" % self[:numero_facture])) if self[:numero_facture]
  end

  def info
    STATUS_LIST[status]
  end

  def update_status
    self.status += 1
    self.save
  end

  def montant(*args)
    if args.count == 0
      self[:montant]
    elsif args[0].is_a?(Modele)
        self.quantite.de(args[0]) * args[0].prix
    end
  end

  def escompte()
    (nombre_paiments == 1) ? 0.03 : 0
  end

  def montant_net_ht()
    montant() * (1 - escompte())
  end

    def tva()
      client.has_tva ? montant_net_ht()*0.20 : 0
    end

  def montant_ttc()
    montant_net_ht() + tva()
  end

  def mensualite
    montant_ttc / nombre_paiments
  end

  def total
    montant_ttc + (frais_de_port || 0) - (avoir || 0)
  end

  def quantite_totale
    self.quantite.total
  end

  def echeancier
    case nombre_paiments
    when 1
      "30"
    when 2
      "15 et 60"
    when 3
      "15, 60 et 90"
    end
  end

  def self.nouveau_numero
    self.where(date_facturation: Time.new.beginning_of_year..Time.now).count + 1
  end

  def +(arg)
    if arg.is_a? Commande
      self.quantite += arg.quantite
    else
      raise ArgumentError, "Opération non définie pour le type #{arg.class}"
    end
    self.update_montant
    self
  end

end

web/app/controllers/commandes_controller.rb
class CommandesController < ApplicationController
  before_action :set_commande, only: [:show, :edit, :update, :destroy]
  before_action :set_catalogue, only: [:show, :new, :create, :edit, :update, :index]

  # GET /commandes
  # GET /commandes.json
  def index

    @commandes = Commande.includes(:quantite,:client)
    @commandes = @commandes.where(status: params[:commande_status].to_i) unless params[:commande_status].blank?

    #@commandes.sort_by { |c| c.send(params[:commande_order] || 'societe')}
    order_value = params[:commande_order] || 'societe'
    @commandes = @commandes.sort_by(&order_value.to_sym)
    #if params[:factures] == 'pro'
   #    @patron=Patron.first
   #   @commandes = @commandes.where(status: 2)
  #    render 'show_all_factures', layout: "printable"
  #  else
      render 'index'
   # end

  end

  # GET /commandes/1
  # GET /commandes/1.json
  def show
    #@modeles=Modele.all(order: 'numero ASC')
    @patron=Patron.first
    if params[:mode] == "livraison"
      filename = "bon-livraison_" + @commande.numero_commande
      render pdf: filename,
        disposition: 'inline',                 # default 'inline'
        template:    'commandes/show_livraison',
        layout:      'printable',
        show_as_html: params[:debug].present?
    elsif params[:mode] == "facture"
      if @commande.status < 2
        filename = "pro-forma_" + @commande.numero_commande
      else
        filename = "facture_" + @commande.numero_facture
      end
      render pdf: filename,
        disposition: 'inline',                 # default 'inline'
        template:    'commandes/show_facture',
        layout:      'printable',
        show_as_html: params[:debug].present? #true
    elsif params[:mode] == "validation"
      @commande.status=3
      @avoir = @commande.client.avoirs_en_attente.to_a.sum(&:total)
      render 'show_validation'
     else
      render 'show'
    end
  end



  # GET /commandes/new
  def new
    if params[:mode] == "print"
      filename = "bon-commande"
      render pdf: filename,
        disposition: 'inline',                 # default 'inline'
        template:    'commandes/new_print',
        layout:      'printable',
        show_as_html: params[:debug].present?
    else
      @commande = Commande.new.prepare
      render 'new'
    end
  end

  # GET /commandes/1/edit
  def edit
    q_new = Commande.new.prepare.quantite
    q_new += @commande.quantite
    @commande.quantite.detail = q_new.detail
  end

  # POST /commandes
  # POST /commandes.json
  def create
    @commande = Commande.new(commande_params)
    if @commande.valid? && @commande.save
      render :show
    else
      render :new
    end
  end


  # PATCH/PUT /commandes/1
  # PATCH/PUT /commandes/1.json
  def update
      case commande_params[:status].to_i
      when 0
        ok=@commande.update(commande_params)
      when 1
        ok=@commande.update(commande_params)
      when 2
        ok=@commande.update(commande_params)
      when 3
        commande_params[:date_facturation] = Time.now
        commande_params[:numero_facture] = Commande.nouveau_numero
        commande_params[:status] = 3
        ok= @commande.update(commande_params)
        if !ok
          @commande.status -= 1
          render action: 'show_validation' and return

          #set_commande
          #render action: 'show_facture', layout: "printable" and return
        end
        #  stock = Stock.find_or_initialize_by_id(1)
        #  stock -= @commande
        #  unless stock.save
        #    @commande.status -= 1
        #    @commande.save
        #    ok = false
        #  end
        #end
      end
    if ok
      @commande.avoirs_en_attente.update_all(status: 1)
      redirect_to @commande
    else
      render action: 'edit'
    end

  end

  # DELETE /commandes/1
  # DELETE /commandes/1.json
  def destroy
    @commande.destroy
    redirect_to commandes_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_commande
      @commande = Commande.where(id: params[:id]).includes(:quantite, :client).first
      if @commande.status == 2
        @commande.update(status: 3)
      end
    end

    def set_catalogue
      @catalogue = Modele.catalogue
      @couleurs = Hash[Couleur.pluck(:id,:nom)]
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def commande_params
      #params[:commande].permit! if params[:commande]
      params.require(:commande).permit!

    end
end

web/app/helpers/commandes_helper.rb
module CommandesHelper
  
  def prix(combien)
    format('%.2f', combien.round(2)) + "&#x20AC;"
  end
  
  def mensualise(commande,texte)
    texte if commande.nombre_paiments > 1
  end

end

web/app/views/commandes/_commande.html.haml
%tr
  %td= link_to ">", commande_path(commande)
  %td= commande.client.societe
  %td= commande.date
  %td!= prix(commande.montant)
  %td= commande.reference
  %td= commande.info

web/app/views/commandes/_form.html.haml
= render "/application/errors", :record => @commande

= form_for @commande, :method=>(@commande.id ? :put : :post) do |f|
  = f.hidden_field :id
  = f.hidden_field :status

  %h2 Client

  = f.label :client_id, 'Commande pour'
  = f.collection_select :client_id, Client.select(:id,:societe).load, :id, :societe, prompt: "-- Selectionnez un client --"

  %h2 Livraison
  = f.label :livraison, "Date de livraison"
  = f.date_select :livraison, order: [:day, :month, :year], start_year: Time.now.year, end_year: Time.now.year+1, month_names: t(:month_names), with_css_classes: true

  %br
  = f.label :commentaire, 'Commentaires'
  = f.text_area :commentaire, size: "30x5"

  %br
  %br
  = f.fields_for :quantite do |ff|
    = render "/quantites/form", {:quantite => @commande.quantite, :f => ff}

web/app/views/commandes/edit.html.haml
%h1 Commande :: modifier
.actions2
  = link_to 'Retour', commande_path(@commande)
  \/
  %a{href: "/", onclick: "document.forms[0].submit(); return false;"} Enregistrer


= render 'form'

web/app/views/commandes/index.html.haml
%h1 Commandes

.actions2
  = link_to ' + Ajouter une comande', new_commande_path()
  = '//'
  = link_to ' > Imprimer un bon de commande', new_commande_path(mode: 'print'), :target => '_blank'


.commande_aide
  %h2 Aide

  .aide_blobs
    .aide_blob
      .aide_head{'data-status' => 0}= 'pré-commande'
    .aide_blob
      .aide_head{'data-status' => 1}= 'en production'
    .aide_blob
      .aide_head{'data-status' => 2}= 'en préparation'
    .aide_blob
      .aide_head{'data-status' => 3}= 'envoyée'
    .aide_blob
      .aide_head{'data-status' => 4}= 'réglée'
  %p
    = "Créez de nouvelles commandes."
    = "Allez dans 'production' pour générer un nouvel ordre de production qui cumulera automatiquement toutes ces pré-commandes."
    = "A la réception de l'arrivage, enregistrez les stocks reçus pour permettre la préparation des commandes."
    = "Une fois envoyée, une commande peut alors être facturée ; elle ne sera alors plus modifiable."

= form_tag commandes_path, method: :get, id: 'commande_filter', class: 'filtre' do
  %h2 Filtre
  %p
    ="Afficher les commandes "
    =select_tag :commande_status, options_for_select(Commande::STATUS_LIST.collect {|k,v| [v,k]}, params[:commande_status]), prompt: "(toutes)",  :onchange => 'this.form.submit();'
    = " triées par "
    =select_tag :commande_order, options_for_select([['client','societe'],['statut','status'],['référence','id'],['montant','montant'],['nbr. de pièces','quantite_totale'],['date de livraison','livraison']],params[:commande_order]),  :onchange => 'this.form.submit();'

.commande_aide
  %h2 Résumé de la sélection
  %p
    = @commandes.count
    = "commandes"
    = "  //  "
    = @commandes.inject(0){ |sum, c| sum+c.quantite.total}
    = "pièces"
    = "  //  "
    != prix(@commandes.sum(&:montant))
    = "HT"

- @commandes.each do |commande|
  .commande_blob{onclick: "window.location = $(this).attr('url')", url: commande_path(commande), 'data-status'=> commande.status}
    .left
      .client= commande.client.societe
      .ref= commande.reference
      .status= commande.info
    .center
      .prix!= prix(commande.montant)
      -#.pieces= "#{@quantite[commande.id]} pcs."
      .pieces= "#{commande.quantite.total} pcs."
    .right
      .lab= "passée le :"
      .date= l commande.created_at.to_date, format: :long
      %br
      .lab= "à livrer  le :"
      .date= l commande.livraison, format: :long

web/app/views/commandes/index2.html.haml
%h1 Commandes


.actions2
  = link_to ' + Ajouter une comande', new_commande_path()

= form_tag commandes_path, method: :get, id: 'commande_filter' do
  = "Afficher les commandes"
  = select_tag :commande_status, options_for_select(Commande::STATUS_LIST.collect {|k,v| [v,k]}, params[:commande_status]), prompt: "(toutes)",  :onchange => 'this.form.submit();'
  = "triées par"
  = select_tag :commande_order, options_for_select([['client','societe'],['date de livraison','livraison'],['référence','reference'],['statut','status']],params[:commande_order]),  :onchange => 'this.form.submit();'
  ="."


%table.listing

  %tr
    %th{width: "250px;", class: ("sorted" if @sorted_by == 'societe')}= 'Client'
    %th{width: "80px;",  class: ("sorted" if @sorted_by == 'livraison')}= 'Livraison'
    %th{width: "80px;",  class: ("sorted" if @sorted_by == 'reference')}= 'Reference'
    %th{width: "100px;",  class: ("sorted" if @sorted_by == 'status')}= 'Statut'

  - @commandes.each do |commande|
    %tr{onclick: "window.location = $(this).attr('url')", url: commande_path(commande)}
      %td= commande.client.societe
      %td.center= commande.date
      %td.center= commande.reference
      %td{class: "info_#{commande.status}"}= commande.info

web/app/views/commandes/new.html.haml
%h1 Commande :: créer
.actions2
  = link_to 'Annuler', commandes_path
  \/
  %a{href: "/", onclick: "document.forms[0].submit(); return false;"} Enregistrer

= render 'form'

web/app/views/commandes/new_print.html.haml
.title
  BlaBla

.bon
  %h1 Bon de commande

  .client
    %p _________________________________________________
    %p _________________________________________________
    %p _________________________________________________
    %p _________________________________________________

  %p.reference
    = "Le __ / ___ / ______,"
    = "commande pour :"
    %br
    = "_________________________________________________"
    %br

  %table.commande
    %tr
      %th= 'Désignation'
      %th{colspan: 7}= 'Tailles'
      %th= 'Total'
    - @catalogue.each do |modele|
      %tr.designation
        %td= "#{modele.numero} - #{modele.nom}"
        - modele.liste_taille.each do |t|
          %td= t
        %td

      - modele.versions.each do |version|
        - couleur = @couleurs[version.couleurs_1_id]
        %tr
          %td= couleur
          - modele.liste_taille.each do |t|
            - if t
              %td
            - else
              %td X
          %td

  .footer
    = "Nombre total de pièces : _____"

web/app/views/commandes/show.html.haml
%h1 Commande
.actions2
  = link_to 'Retour', commandes_path
  - if @commande.status < 3
    \/
    = link_to "Modifier", edit_commande_path(@commande)
    \/
    = link_to 'Supprimer', @commande, :method => :delete, :data => { :confirm => 'Etes-vous sur de vouloir supprimer cette commande ?' }

%h2 Infos
%p!= "Commande passée le #{@commande.date} pour #{@commande.client.societe} pour un montant total de #{prix(@commande.montant)} HT."
%p= @commande.commentaire

%h2 Statut
- if @commande.status == 0
  %p= "Ceci est une pré-commande. Elle sera automatiquement intégrée à la prochaine production. Procédez à la production et réceptionnez le stock avant de continuer."
- if @commande.status == 1 || @commande.status == 2
  %p
    = "Imprimer le "
    = link_to 'bon de livraison', commande_path(@commande, mode: 'livraison'), :target => '_blank'
    = '.'
  %p
    = "Imprimer le "
    = link_to 'pro forma', commande_path(@commande, mode: 'facture'), :target => '_blank'
    = '.'
  %p
    = "Une fois la commande expédiée, vous pouvez"
    = link_to 'procéder à la facturation', commande_path(@commande, mode: 'validation')
    = ". Attention ! Il ne sera plus possible de modifier la commande une la facture crée !"
- if @commande.status == 3
  %p
    = "Cette commande a été facturée. Voir la"
    = link_to 'facture', commande_path(@commande, mode: 'facture'), :target => '_blank'
    = "."



%h2 Détail
= render "/quantites/show", :quantite => @commande.quantite

web/app/views/commandes/show_all_factures.html.haml
= render partial: "show_facture", collection: @commandes,  as: :commande

web/app/views/commandes/show_facture.html.haml
.title
  BlaBla 81

.bon
  - if @commande.status < 3
    %h1 Pro Forma
  - else
    %h1 Facture

  .informations
    %p= @patron.intitule
    %p!= "#{@patron.adresse.gsub("\r\n",", ")}"
    %p!= "SASU au capital de 5000&#x20AC;"
    %p= "RCS: 823359757 Albi - TVA: FR85823359757"
    %p= "#{@patron.telephone}"
    %p= "#{@patron.email}"

  .client
    %p= @commande.client.societe
    %p= @commande.client.nom
    %p=raw to_html(@commande.client.adresse_1)

  %p.reference
    - if @commande.status < 3
      = "Le #{Time.now.strftime('%d/%m/%Y')}, commande référence #{@commande.reference} pour :"
    - else
      = "Le #{@commande.date_facturation.strftime('%d/%m/%Y')}, facture n° #{@commande.numero_facture} pour :"
    -#%br
    = @commande.client.intitule
    = "(#{@commande.client.identification})"

  - if @commande.status < 3
    %p.alert
      = "Attention ! Ceci n'est pas une facture : elle n'inclut pas les frais de livraison ni"
      = "les changements qui peuvent intervenir d'ici l'envoi de votre commande. Le montant réel "
      = "sera indiqué sur la facture définitive qui vous sera envoyée ultérieurement."

  %table.commande
    %tr.designation
      %th{width: "400px;"} Désignation
      %th{width: "60px;"} Qnt
      %th{width: "80px;"} PU HT
      %th{width: "80px;"} Mnt HT
    - @commande.quantite.modeles_ids(@catalogue).each do |modele_id|
      - modele=@catalogue.select {|m| m.id == modele_id.to_i}.first
      - if @commande.quantite.de(modele) > 0
        %tr.facture
          %td= "#{modele.numero} - #{modele.nom}"
          %td= @commande.quantite.de(modele)
          %td!= "#{prix(modele.prix)}"
          %td!= "#{prix(@commande.montant(modele))}"
    %tr.sep
      %td{colspan: 4}
    %tr.blank
      %td
      %td.total{colspan: 2} Total HT
      %td.total!= "#{prix(@commande.montant)}"
    - if @commande.escompte > 0
      %tr.blank
        %td.info="3% du Total HT pour paiment en 1 fois."
        %td.total{colspan: 2} Escompte
        %td.total!= "- #{prix(@commande.montant * @commande.escompte)}"
      %tr.blank
        %td
        %td.total{colspan: 2} Net HT
        %td.total!= "#{prix(@commande.montant_net_ht)}"
    %tr.blank
      -if @commande.client.has_tva
        %td.info="Base TVA: 20.0\%"
      - else
        %td.info= "TVA non applicable, art. 293 B du CGI"
      %td.total{colspan: 2} TVA
      %td.total!= "#{prix(@commande.tva)}"
    %tr.blank
      %td.info{rowspan: @commande.status >= 3 ? 3:2}
        - if @commande.status < 3
          != "L'envoi de votre commande sera effectuée après la réception de tous les chèques. "
          != "En dessous de 500&#x20AC;, encaissement en une fois à 30 jours après livraison."
          != "Au delà, encaissement en trois fois à 15, 60 et 90 jours (30%, 30%, et 40%)."
          != "Les chèques sont à mettre à l'ordre de BLABLA 81"
        - else
          != "Payable par chèque pour la somme de #{prix(@commande.total)},"
          != "soit #{pluralize(@commande.nombre_paiments,'paiement')} à valoir sous"
          != "#{@commande.echeancier} jours #{mensualise(@commande,"respectivement")} à partir de la date de livraison."
          != "L'envoi de votre commande sera effectuée après la réception des chèques."
          != "Les chèques sont à mettre à l'ordre de BLABLA 81"
      %td.total{colspan: 2} Total TTC
      %td.total!= "#{prix(@commande.montant_ttc)}"
    - if @commande.status >= 3
      %tr.blank
        %td.total{colspan: 2} Frais de port
        %td.total!= "#{prix(@commande.frais_de_port)}"
        - if @commande.avoir > 0
          %tr.blank
          %td
          %td.total{colspan: 2} Avoir
          %td.total!= "- #{prix(@commande.avoir)}"
    %tr.blank
      - if @commande.avoir > 0
        %td
      %td.grandtotal{colspan: 2} Net à payer
      %td.grandtotal!= "#{prix(@commande.total)}"
    %tr.sep
      %td{colspan: 4}

  %p.legislation
    != "Pénalité de retard: 3% (taux annuel) plus une indemnité forfaitaire de 40&#x20AC; pour frais de recouvrement."
    = "Escompte pour paiement anticipé: néant."
    != "Droit de réserve&nbsp;: nous nous réservons la propriété des marchandises jusqu'au paiement du prix par l'acheteur&nbsp;;"
    = "ce droit de revendication porte aussi bien sur les marchandises que sur leur prix si elles ont déjà été revendues (Loi du 12 mai 1989)."

web/app/views/commandes/show_livraison.html.haml
.title
  BlaBla 81

.bon
  %h1 Bon de livraison

  .client
    %p= @commande.client.societe
    %p= @commande.client.nom
    %p=raw to_html(@commande.client.adresse_2)

  %p.reference
    = "Le #{Date.today.strftime('%d/%m/%Y')},"
    = "commande n°#{@commande.reference} pour :"
    = "#{@commande.client.intitule} (#{@commande.client.identification})"

  %table.commande
    %tr
      %th= 'Désignation'
      %th{colspan: 7}= 'Tailles'
      %th= 'Total'
    - @commande.quantite.modeles_ids(@catalogue).each do |modele_id|
      - modele=@catalogue.select {|m| m.id == modele_id.to_i}.first
      - if @commande.quantite.de(modele) > 0
        %tr.designation
          %td= "#{modele.numero} - #{modele.nom}"
          - modele.liste_taille.each do |t|
            %td= t
          %td= @commande.quantite.de(modele.id)

        - @commande.quantite.versions_ids(modele.id).each do |version_id|
          - version=modele.versions.select {|v| v.id == version_id.to_i}.first
          - couleur=@couleurs[version.couleurs_1_id]
          - if @commande.quantite.de(version) > 0
            %tr
              %td= couleur
              - modele.liste_taille.each do |t|
                %td= @commande.quantite.de(version,t) if t
              %td= @commande.quantite.de(version)

  .footer
    = "Nombre total de pièces : #{@commande.quantite.de}"

web/app/views/commandes/show_validation.html.haml
%h1 Commande
.actions2
  = link_to 'Retour', commande_path(@commande)
  \/
  %a{href: "/", onclick: "document.forms[0].submit(); return false;"} Enregistrer

%p
  = "Vous-êtes sur le point de facturer la commande n° #{@commande.numero_commande} pour #{@commande.client.societe}, "
  != "d'un montant total de #{prix(@commande.montant)} HT."
%p
  = "Ce client #{@commande.client.has_tva ? 'est' : 'n\'est pas'} soumis à la TVA."

%p= "Après validation, vous ne pourrez plus modifier cette commande !"

%h2 Détails de la facturation
%p= render "/application/errors", :record => @commande

= form_for @commande do |f|
  = f.hidden_field :id
  = f.hidden_field :status
  = f.hidden_field :date_facturation
  = f.hidden_field :numero_facture

  = f.label :frais_de_port, "Frais de port (euros)"
  = f.number_field :frais_de_port
  %br
  = f.label :frais_de_port, "Avoir (euros)"
  = f.number_field :avoir, value: @avoir, :readonly => true
  %br
  = f.label "Facilité de paiment"
  = f.select :nombre_paiments, options_for_select((1..3).collect {|i| ["en #{i} fois #{(i==1) ? '(- 3%)' : ''}", i]} )